import "highlight.js/styles/github.css";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata: Metadata = {
  title: "TezX",
  description: "Generated by ",
};

import React from "react";

type Props = {
  children: React.ReactNode;
};

export default function PackageLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className="h-full">
        <Toaster position="top-center" reverseOrder={false} />
        {children}
      </body>
    </html>
  );
}

// export function generateStaticParams(props: { params: { path: any } }) {
//   return docs?.files?.filter(r => r.path).map(r => {
//     return {
//       path: r?.path?.split("/"),
//     }
//   })
// }
