import { cors } from "./cors.js";
import { logger } from "./logger.js";
export * from "./basicAuth.js";
export * from "./cacheControl.js";
export * from "./cors.js";
export { detectBot } from "./detectBot.js";
export type { DetectBotReason } from "./detectBot.js";
export * from "./detectLocale.js";
export * from "./i18n.js";
export * from "./lazyLoader.js";
export * from "./logger.js";
export * from "./pagination.js";
export * from "./powered-by.js";
export * from "./rateLimiter.js";
export * from "./request-id.js";
export * from "./requestTimeout.js";
export * from "./sanitizeHeader.js";
export * from "./secureHeaders.js";
export * from "./xssProtection.js";
declare const _default: {
    basicAuth: (options: import("./basicAuth.js").DynamicBasicAuthOptions) => import("../index.js").Middleware;
    cacheControl: (options: import("./cacheControl.js").CacheOptions) => import("../index.js").Middleware;
    cors: typeof cors;
    detectBot: (options?: import("./detectBot.js").DetectBotOptions) => import("../index.js").Middleware;
    detectLocale: (options: import("./detectLocale.js").DetectLocaleOptions) => import("../index.js").Middleware;
    i18n: (options: import("./i18n.js").I18nOptions) => import("../index.js").Middleware;
    lazyLoader: <T = any>(options: import("./lazyLoader.js").LazyLoadOptions<T>) => import("../index.js").Middleware;
    logger: typeof logger;
    paginationHandler: (options?: import("./pagination.js").PaginationOptions) => import("../index.js").Middleware;
    poweredBy: (serverName?: string) => import("../index.js").Middleware;
    rateLimiter: (options: import("./rateLimiter.js").RateLimiterOptions) => import("../index.js").Middleware;
    requestID: (headerName?: string, contextKey?: string) => import("../index.js").Middleware;
    requestTimeout: (options: import("./requestTimeout.js").TimeoutOptions) => import("../index.js").Middleware;
    sanitizeHeaders: (options?: import("./sanitizeHeader.js").SanitizeHeadersOptions) => import("../index.js").Middleware;
    secureHeaders: (options?: import("./secureHeaders.js").SecurityHeaderOptions) => import("../index.js").Middleware;
    xssProtection: (options?: import("./xssProtection.js").XSSProtectionOptions) => (ctx: import("../index.js").BaseContext, next: import("../index.js").NextCallback) => Promise<any>;
};
export default _default;
