import { Router } from "./core/router.js";
import { TezX } from "./core/server.js";
import { useParams } from "./utils/params.js";
export { Router } from "./core/router.js";
export type { Callback, ctx as Context, Middleware, NextCallback, RouterConfig, StaticServeOption } from "./core/router.js";
export type { AdapterType } from "./core/config.js";
export type { CookieOptions, ResponseHeaders } from "./core/context.js";
export type { NetAddr as AddressType, ConnAddress, FormDataOptions, HTTPMethod } from "./core/request.js";
export { TezX } from "./core/server.js";
export type { TezXConfig, TezXServeOptions } from "./core/server.js";
export type { UrlRef } from "./utils/url.js";
export { useParams };
export declare let version: string;
declare const _default: {
    Router: typeof Router;
    TezX: typeof TezX;
    useParams: typeof useParams;
    version: string;
};
export default _default;
